rvm: 1.9.3
notifications:
  email:
    - icalvete@gmail.com
env:
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.3.0
install: travis_retry bundle install
before_script:
  - chmod +x ./script/cibuild
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib.git spec/fixtures/modules/stdlib'
script: 
  - './script/cibuild'
  - 'bundle exec rake' 
